import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-weekly-feedback-form',
    templateUrl: './weekly-feedback-form.component.html',
    styleUrls: ['./weekly-feedback-form.component.scss'],
})
export class WeeklyFeedbackFormComponent implements OnInit {
    public form!: Object;
    constructor() {}

    ngOnInit(): void {
        this.form = {
            components: [
                {
                    label: 'Overall Status',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description:
                        'This depicts the overall status of the project, Here Green means, Everything is good and no mgmt action is needed. Yellow means mgmt action is needed but not immediately, Red means immediate mgmt action is needed.',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: '',
                    data: {
                        values: [
                            {
                                label: 'green',
                                value: 'green',
                            },
                            {
                                label: 'yellow',
                                value: 'yellow',
                            },
                            {
                                label: 'red',
                                value: 'red',
                            },
                        ],
                        resource: '',
                        json: '',
                        url: '',
                        custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        onlyAvailableItems: false,
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'overallStatus',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'select',
                    indexeddb: {
                        filter: {},
                    },
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    dataGridLabel: false,
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    lazyLoad: true,
                    authenticate: false,
                    ignoreCache: false,
                    fuseOptions: {
                        include: 'score',
                        threshold: 0.3,
                    },
                    id: 'e38o3lg',
                },
                {
                    label: 'Risks',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description:
                        'Green - No foreseen risks are seen in this project. Yellow - There might be some risk involved and Red - High risks in this project',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: '',
                    data: {
                        values: [
                            {
                                label: 'green',
                                value: 'green',
                            },
                            {
                                label: 'yellow',
                                value: 'yellow',
                            },
                            {
                                label: 'red',
                                value: 'red',
                            },
                        ],
                        resource: '',
                        json: '',
                        url: '',
                        custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        onlyAvailableItems: false,
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'risks',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'select',
                    indexeddb: {
                        filter: {},
                    },
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    dataGridLabel: false,
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    lazyLoad: true,
                    authenticate: false,
                    ignoreCache: false,
                    fuseOptions: {
                        include: 'score',
                        threshold: 0.3,
                    },
                    id: 'ew93qgc',
                },
                {
                    label: 'Schedule',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description:
                        'Green - Everything is delivered on or before time. Yellow - Deliveries are delayed somewhat. Red - Deliveries are impacted a lot and need immediate solution.',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: '',
                    data: {
                        values: [
                            {
                                label: 'green',
                                value: 'green',
                            },
                            {
                                label: 'yellow',
                                value: 'yellow',
                            },
                            {
                                label: 'red',
                                value: 'red',
                            },
                        ],
                        resource: '',
                        json: '',
                        url: '',
                        custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        onlyAvailableItems: false,
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'schedule',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'select',
                    indexeddb: {
                        filter: {},
                    },
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    dataGridLabel: false,
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    lazyLoad: true,
                    authenticate: false,
                    ignoreCache: false,
                    fuseOptions: {
                        include: 'score',
                        threshold: 0.3,
                    },
                    id: 'ecsonc',
                },
                {
                    label: 'Client Satisfaction',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description:
                        'Green - Client is satisfied and ready to give reference, more work etc. Yellow - Client is somewhat unhappy for various reasons, Red - Client is not happy at all and need immediate attention.',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: '',
                    data: {
                        values: [
                            {
                                label: 'green',
                                value: 'green',
                            },
                            {
                                label: 'yellow',
                                value: 'yellow',
                            },
                            {
                                label: 'red',
                                value: 'red',
                            },
                        ],
                        resource: '',
                        json: '',
                        url: '',
                        custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        onlyAvailableItems: false,
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'clientSatisfaction',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'select',
                    indexeddb: {
                        filter: {},
                    },
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    dataGridLabel: false,
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    lazyLoad: true,
                    authenticate: false,
                    ignoreCache: false,
                    fuseOptions: {
                        include: 'score',
                        threshold: 0.3,
                    },
                    id: 'eoja2mx',
                },
                {
                    label: 'Resources',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description:
                        'Green - Everything is good on resources side, no foreseen issues. Yellow - There might be some issues due to resources in near future and can affect sprint deliveries etc, need mgmt attention and solution soon. Red - Huge problem with resources, need immediate attention.',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: '',
                    data: {
                        values: [
                            {
                                label: 'green',
                                value: 'green',
                            },
                            {
                                label: 'yellow',
                                value: 'yellow',
                            },
                            {
                                label: 'red',
                                value: 'red',
                            },
                        ],
                        resource: '',
                        json: '',
                        url: '',
                        custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        onlyAvailableItems: false,
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'resources',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'select',
                    indexeddb: {
                        filter: {},
                    },
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    dataGridLabel: false,
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    lazyLoad: true,
                    authenticate: false,
                    ignoreCache: false,
                    fuseOptions: {
                        include: 'score',
                        threshold: 0.3,
                    },
                    id: 'e6o6rpq',
                },
                {
                    label: 'Budget',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description:
                        'Green - Project is within the planned budget(Resources etc), Yellow - Budget is crossed a bit due to delays, issues etc at our end, Red - huge difference in original and actual budget due to different reasons',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: '',
                    data: {
                        values: [
                            {
                                label: 'green',
                                value: 'green',
                            },
                            {
                                label: 'yellow',
                                value: 'yellow',
                            },
                            {
                                label: 'red',
                                value: 'red',
                            },
                        ],
                        resource: '',
                        json: '',
                        url: '',
                        custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        onlyAvailableItems: false,
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'budget',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'select',
                    indexeddb: {
                        filter: {},
                    },
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    dataGridLabel: false,
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    lazyLoad: true,
                    authenticate: false,
                    ignoreCache: false,
                    fuseOptions: {
                        include: 'score',
                        threshold: 0.3,
                    },
                    id: 'eobee39',
                },
                {
                    label: 'Overall Comments',
                    labelPosition: 'top',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    displayMask: '',
                    editor: '',
                    autoExpand: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'html',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        minWords: '',
                        maxWords: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'overallComments',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textarea',
                    rows: 3,
                    wysiwyg: false,
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    allowMultipleMasks: false,
                    addons: [],
                    mask: false,
                    inputType: 'text',
                    inputMask: '',
                    fixedSize: true,
                    id: 'e2i0v7',
                },
                {
                    label: 'Prepared By',
                    labelPosition: 'top',
                    placeholder: '',
                    description: 'Enter project manager name',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'preparedBy',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'ett1jc',
                },
                {
                    label: 'Tasks Accomplished this week',
                    labelPosition: 'top',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    displayMask: '',
                    editor: '',
                    autoExpand: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'html',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        minWords: '',
                        maxWords: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'tasksAccomplishedThisWeek',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textarea',
                    rows: 3,
                    wysiwyg: false,
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    allowMultipleMasks: false,
                    addons: [],
                    mask: false,
                    inputType: 'text',
                    inputMask: '',
                    fixedSize: true,
                    id: 'ex00bzb',
                },
                {
                    label: 'Tasks planned for next week',
                    labelPosition: 'top',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    displayMask: '',
                    editor: '',
                    autoExpand: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'html',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        minWords: '',
                        maxWords: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'tasksPlannedForNextWeek',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textarea',
                    rows: 3,
                    wysiwyg: false,
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    allowMultipleMasks: false,
                    addons: [],
                    mask: false,
                    inputType: 'text',
                    inputMask: '',
                    fixedSize: true,
                    id: 'epkf5qo',
                },
                {
                    label: 'Key issue #1',
                    labelPosition: 'top',
                    placeholder: '',
                    description:
                        'Here mention key issue, risks and concerns if any which can effect cost, schedule or resources. We need to be proactive in updating client. For multiple issues submit questions separately from below list',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'keyIssue1',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'ed3uaoq',
                },
                {
                    label: 'Key issue #2',
                    labelPosition: 'top',
                    placeholder: '',
                    description:
                        'Here mention key issue, risks and concerns if any which can effect cost, schedule or resources. We need to be proactive in updating client. For multiple issues submit questions separately from below list',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'keyIssue2',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'eph4e9f',
                },
                {
                    label: 'Key issue #3',
                    labelPosition: 'top',
                    placeholder: '',
                    description:
                        'Here mention key issue, risks and concerns if any which can effect cost, schedule or resources. We need to be proactive in updating client. For multiple issues submit questions separately from below list',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'keyIssue3',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'epghlev',
                },
                {
                    label: 'Key issue #4',
                    labelPosition: 'top',
                    placeholder: '',
                    description:
                        'Here mention key issue, risks and concerns if any which can effect cost, schedule or resources. We need to be proactive in updating client. For multiple issues submit questions separately from below list',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'keyIssue4',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'evduyv',
                },
                {
                    label: 'Key issue #5',
                    labelPosition: 'top',
                    placeholder: '',
                    description:
                        'Here mention key issue, risks and concerns if any which can effect cost, schedule or resources. We need to be proactive in updating client. For multiple issues submit questions separately from below list',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'keyIssue5',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'ejulew',
                },
                {
                    label: 'Overall Status-Client',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: '',
                    data: {
                        values: [
                            {
                                label: 'green',
                                value: 'green',
                            },
                            {
                                label: 'yellow',
                                value: 'yellow',
                            },
                            {
                                label: 'red',
                                value: 'red',
                            },
                        ],
                        resource: '',
                        json: '',
                        url: '',
                        custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        onlyAvailableItems: false,
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'overallStatusClient',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'select',
                    indexeddb: {
                        filter: {},
                    },
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    dataGridLabel: false,
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    lazyLoad: true,
                    authenticate: false,
                    ignoreCache: false,
                    fuseOptions: {
                        include: 'score',
                        threshold: 0.3,
                    },
                    id: 'eh9rj5a',
                },
                {
                    label: 'Overall Status - Summary',
                    labelPosition: 'top',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'overallStatusSummary',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'e1qvpi',
                },
                {
                    label: 'Schedule Status-Client',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: '',
                    data: {
                        values: [
                            {
                                label: 'green',
                                value: 'green',
                            },
                            {
                                label: 'yellow',
                                value: 'yellow',
                            },
                            {
                                label: 'red',
                                value: 'red',
                            },
                        ],
                        resource: '',
                        json: '',
                        url: '',
                        custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        onlyAvailableItems: false,
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'scheduleStatusClient',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'select',
                    indexeddb: {
                        filter: {},
                    },
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    dataGridLabel: false,
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    lazyLoad: true,
                    authenticate: false,
                    ignoreCache: false,
                    fuseOptions: {
                        include: 'score',
                        threshold: 0.3,
                    },
                    id: 'e7gekm',
                },
                {
                    label: 'Schedule Status - Summary',
                    labelPosition: 'top',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'scheduleStatusSummary',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'euvs7i',
                },
                {
                    label: 'Scope Status-Client',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: '',
                    data: {
                        values: [
                            {
                                label: 'green',
                                value: 'green',
                            },
                            {
                                label: 'yellow',
                                value: 'yellow',
                            },
                            {
                                label: 'red',
                                value: 'red',
                            },
                        ],
                        resource: '',
                        json: '',
                        url: '',
                        custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        onlyAvailableItems: false,
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'scopeStatusClient',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'select',
                    indexeddb: {
                        filter: {},
                    },
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    dataGridLabel: false,
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    lazyLoad: true,
                    authenticate: false,
                    ignoreCache: false,
                    fuseOptions: {
                        include: 'score',
                        threshold: 0.3,
                    },
                    id: 'en0x2ga',
                },
                {
                    label: 'Scope Status - Summary',
                    labelPosition: 'top',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'scopeStatusSummary',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'ehvs4rd',
                },
                {
                    label: 'Resource Status-Client',
                    labelPosition: 'top',
                    widget: 'choicesjs',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    customClass: '',
                    tabindex: '',
                    hidden: false,
                    hideLabel: false,
                    uniqueOptions: false,
                    autofocus: false,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    dataSrc: 'values',
                    defaultValue: '',
                    data: {
                        values: [
                            {
                                label: 'green',
                                value: 'green',
                            },
                            {
                                label: 'yellow',
                                value: 'yellow',
                            },
                            {
                                label: 'red',
                                value: 'red',
                            },
                            {
                                label: 'na',
                                value: 'na',
                            },
                        ],
                        resource: '',
                        json: '',
                        url: '',
                        custom: '',
                    },
                    dataType: '',
                    idPath: 'id',
                    valueProperty: '',
                    template: '<span>{{ item.label }}</span>',
                    refreshOn: '',
                    refreshOnBlur: '',
                    clearOnRefresh: false,
                    searchEnabled: true,
                    selectThreshold: 0.3,
                    readOnlyValue: false,
                    customOptions: {},
                    useExactSearch: false,
                    persistent: true,
                    protected: false,
                    dbIndex: false,
                    encrypted: false,
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        onlyAvailableItems: false,
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'resourceStatusClient',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'select',
                    indexeddb: {
                        filter: {},
                    },
                    selectFields: '',
                    searchField: '',
                    searchDebounce: 0.3,
                    minSearch: 0,
                    filter: '',
                    limit: 100,
                    redrawOn: '',
                    input: true,
                    prefix: '',
                    suffix: '',
                    dataGridLabel: false,
                    showCharCount: false,
                    showWordCount: false,
                    allowMultipleMasks: false,
                    addons: [],
                    lazyLoad: true,
                    authenticate: false,
                    ignoreCache: false,
                    fuseOptions: {
                        include: 'score',
                        threshold: 0.3,
                    },
                    id: 'eqqzsqs',
                },
                {
                    label: 'Resource Status - Summary',
                    labelPosition: 'top',
                    placeholder: '',
                    description: '',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'resourceStatusSummary',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'euzf2d',
                },
                {
                    label: 'Client Email Addresses',
                    labelPosition: 'top',
                    placeholder: '',
                    description: 'Enter email addresses separated by comma',
                    tooltip: '',
                    prefix: '',
                    suffix: '',
                    widget: {
                        type: 'input',
                    },
                    inputMask: '',
                    displayMask: '',
                    allowMultipleMasks: false,
                    customClass: '',
                    tabindex: '',
                    autocomplete: '',
                    hidden: false,
                    hideLabel: false,
                    showWordCount: false,
                    showCharCount: false,
                    mask: false,
                    autofocus: false,
                    spellcheck: true,
                    disabled: false,
                    tableView: true,
                    modalEdit: false,
                    multiple: false,
                    defaultValue: '',
                    persistent: true,
                    inputFormat: 'plain',
                    protected: false,
                    dbIndex: false,
                    case: '',
                    truncateMultipleSpaces: false,
                    encrypted: false,
                    redrawOn: '',
                    clearOnHide: true,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    allowCalculateOverride: false,
                    validateOn: 'change',
                    validate: {
                        required: false,
                        pattern: '',
                        customMessage: '',
                        custom: '',
                        customPrivate: false,
                        json: '',
                        minLength: '',
                        maxLength: '',
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    unique: false,
                    errorLabel: '',
                    errors: '',
                    key: 'clientEmailAddressEs',
                    tags: [],
                    properties: {},
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                        json: '',
                    },
                    customConditional: '',
                    logic: [],
                    attributes: {},
                    overlay: {
                        style: '',
                        page: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    type: 'textfield',
                    input: true,
                    refreshOn: '',
                    dataGridLabel: false,
                    addons: [],
                    inputType: 'text',
                    id: 'etvmgpq',
                },
                {
                    type: 'button',
                    label: 'Submit',
                    key: 'submit',
                    size: 'md',
                    block: false,
                    action: 'submit',
                    disableOnInvalid: true,
                    theme: 'primary',
                    input: true,
                    placeholder: '',
                    prefix: '',
                    customClass: '',
                    suffix: '',
                    multiple: false,
                    defaultValue: null,
                    protected: false,
                    unique: false,
                    persistent: false,
                    hidden: false,
                    clearOnHide: true,
                    refreshOn: '',
                    redrawOn: '',
                    tableView: false,
                    modalEdit: false,
                    dataGridLabel: true,
                    labelPosition: 'top',
                    description: '',
                    errorLabel: '',
                    tooltip: '',
                    hideLabel: false,
                    tabindex: '',
                    disabled: false,
                    autofocus: false,
                    dbIndex: false,
                    customDefaultValue: '',
                    calculateValue: '',
                    calculateServer: false,
                    widget: {
                        type: 'input',
                    },
                    attributes: {},
                    validateOn: 'change',
                    validate: {
                        required: false,
                        custom: '',
                        customPrivate: false,
                        strictDateValidation: false,
                        multiple: false,
                        unique: false,
                    },
                    conditional: {
                        show: null,
                        when: null,
                        eq: '',
                    },
                    overlay: {
                        style: '',
                        left: '',
                        top: '',
                        width: '',
                        height: '',
                    },
                    allowCalculateOverride: false,
                    encrypted: false,
                    showCharCount: false,
                    showWordCount: false,
                    properties: {},
                    allowMultipleMasks: false,
                    addons: [],
                    leftIcon: '',
                    rightIcon: '',
                    id: 'eu3n0v',
                },
            ],
        };
    }

    submit(event: any) {
        console.log(event);
    }
}
